# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # Treat missing required parameters as a warning (not error)
    missing_required_param: warning
    # Treat missing returns as a warning (not error)
    missing_return: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/generated/**"
    - "**/build/**"

linter:
  rules:
    # Keep existing rules
    avoid_shadowing_type_parameters: false
    await_only_futures: true
    non_constant_identifier_names: false
    prefer_const_constructors: false
    use_key_in_widget_constructors: false
    prefer_const_declarations: false
    prefer_const_literals_to_create_immutables: false
    avoid_print: false
    prefer_const_constructors_in_immutables: false
    avoid_unnecessary_containers: false

    # Code style
    prefer_single_quotes: true
    lines_longer_than_80_chars: false
    public_member_api_docs: false
    always_put_required_named_parameters_first: true
    avoid_private_typedef_functions: false
    avoid_redundant_argument_values: true
    avoid_returning_null_for_void: true
    avoid_unused_constructor_parameters: true
    curly_braces_in_flow_control_structures: true
    prefer_conditional_assignment: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_null_aware_operators: true
    prefer_void_to_null: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    type_init_formals: true
    unawaited_futures: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: true
    use_string_buffers: true
    valid_regexps: true
    
    # Flutter specific
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    always_specify_types: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_as: false
    avoid_bool_literals_in_conditional_expressions: true
    avoid_catches_without_on_clauses: true
    avoid_catching_errors: true
    avoid_classes_with_only_static_members: true
    avoid_empty_else: true
    avoid_equals_and_hash_code_on_mutable_classes: true
    avoid_field_initializers_in_const_classes: true
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: true
    avoid_init_to_null: true
    avoid_js_rounded_ints: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_this: true
    avoid_setters_without_getters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_as_parameter_names: true
    avoid_void_async: true
    avoid_web_libraries_in_flutter: true
    cancel_subscriptions: true
    cascade_invocations: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    directives_ordering: true
    file_names: true
    flutter_style_todos: true
    implementation_imports: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    join_return_with_assignment: true
    library_names: true
    library_prefixes: true
    list_remove_unrelated_type: true
    literal_only_boolean_expressions: true
    missing_whitespace_between_adjacent_strings: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    no_runtimeType_toString: true
    null_closures: true
    omit_local_variable_types: false
    only_throw_errors: true
    overridden_fields: true
    package_api_docs: false
    package_names: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_asserts_with_message: true
    prefer_collection_literals: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_expression_function_bodies: true
    prefer_final_in_for_each: true
    prefer_initializing_formals: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_mixin: true
    prefer_null_aware_method_calls: true
    prefer_relative_imports: true
    prefer_spread_collections: true
    slash_for_doc_comments: true
    sort_pub_dependencies: true
    throw_in_finally: true
    type_annotate_public_apis: true
    use_build_context_synchronously: true
    use_function_type_syntax_for_parameters: true

