name: seemytrip
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  flutter_svg: ^2.1.0
  pinput: ^1.2.2
  carousel_slider: ^5.0.0
  table_calendar: ^3.0.8
  flutter_toggle_tab: ^1.2.0
  http: ^1.2.2
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2
  multi_select_flutter: ^4.1.3
  timelines_plus: ^1.0.6
  webview_flutter_android: ^4.4.2
  webview_flutter: ^4.11.0
  lottie: ^3.3.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_gen: ^5.10.0
  photo_view: ^0.15.0
  url_launcher: ^6.3.1
  latlong2: ^0.9.1
  flutter_map: ^8.1.1
  html: ^0.15.4
  flutter_html: ^3.0.0
  google_fonts: ^6.1.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  dotted_line: ^3.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/seemytrip_mobile_appLogo_withoutBackground.png"
  min_sdk_android: 21 # Android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/seemytrip_mobile_appLogo_withoutBackground.png"
  windows:
    generate: true
    image_path: "assets/images/seemytrip_mobile_appLogo_withoutBackground.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  generate: true


  assets:
    - assets/images/
    - assets/images/SelectCountryScreenImages/
    - assets/jsons/travel_animation.json

 
  fonts:
  - family: PoppinsBold
    fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
  - family: PoppinsLight
    fonts:
      - asset: assets/fonts/Poppins-Light.ttf
  - family: PoppinsMedium
    fonts:
      - asset: assets/fonts/Poppins-Medium.ttf
  - family: PoppinsRegular
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
  - family: PoppinsSemiBold
    fonts:
      - asset: assets/fonts/Poppins-SemiBold.ttf
