// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqFw3wf7RZxUumfpToOHLY-aqYSER_S-k',
    appId: '1:579307150474:android:29ccedb62029ad3310e173',
    messagingSenderId: '579307150474',
    projectId: 'seemytrip-78ee6',
    storageBucket: 'seemytrip-78ee6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQCYB5GErw-Ab5ObpJlk7kH2sYO0ux7n0',
    appId: '1:579307150474:ios:173df959abd14db410e173',
    messagingSenderId: '579307150474',
    projectId: 'seemytrip-78ee6',
    storageBucket: 'seemytrip-78ee6.firebasestorage.app',
    iosBundleId: 'com.example.seemytrip',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5atD2yyVmwBj8owvgWmbkS3Gq_SSbwCw',
    appId: '1:579307150474:web:37e3521977be666810e173',
    messagingSenderId: '579307150474',
    projectId: 'seemytrip-78ee6',
    authDomain: 'seemytrip-78ee6.firebaseapp.com',
    storageBucket: 'seemytrip-78ee6.firebasestorage.app',
    measurementId: 'G-06BR5ZEQ4D',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQCYB5GErw-Ab5ObpJlk7kH2sYO0ux7n0',
    appId: '1:579307150474:ios:173df959abd14db410e173',
    messagingSenderId: '579307150474',
    projectId: 'seemytrip-78ee6',
    storageBucket: 'seemytrip-78ee6.firebasestorage.app',
    iosBundleId: 'com.example.seemytrip',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5atD2yyVmwBj8owvgWmbkS3Gq_SSbwCw',
    appId: '1:579307150474:web:53e83732c1d2d70710e173',
    messagingSenderId: '579307150474',
    projectId: 'seemytrip-78ee6',
    authDomain: 'seemytrip-78ee6.firebaseapp.com',
    storageBucket: 'seemytrip-78ee6.firebasestorage.app',
    measurementId: 'G-6C7NP05S6G',
  );

}